language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
- nightly
env:
- TOXENV=pytest29
- TOXENV=pytest30
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 3.5
    env: TOXENV=flake8
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: davehunt
  password:
    secure: a2VxLM2dFEHOUa3WqTJ3TRTnO/F5rb6bJ5bLVdgoIj2jRWLw+eCkNCh0akv4lKQEjhXoZiAsKizQbR7ioEF/LE0IZj84bov4NUwWZdcADgG+tUXxJHNreQlLvcdXHmz0qP6TfylEDuIMX5meV3v+baNcgFgds8mK7oNQq9Xywh2QNxUgyAKhiMsGJ/DhP3Zs0NdYKLWs1ElHBTP4eJZvYa1IFg/JS4ierzVbg3znrbYVy26Qp9Yj3XqaIF5DaR2boNW47IB3n5N3a0LI/0bwRTABp7rWy18hjlFxowtGSjxnezZvbReZYtZFN4FASiSDfoA8Hl6/jxjLOupcwuR8H+/OXh1Dvj5n0IgYCWxRJY+P9fAQ3Is9W5p3v9REjBHcuoIcKFL/Ne7MffzALRR1L4CROo67WlOGHf3i/kh3zdy/j8b5Ngmem/isSDWkU5YIyI1dBe6BrCD+vhDQlgaWSynMqyOe1JVxgbCF1z4T+Dtu8U6jlBpA5QmB97MifjpWpJW43T2cpqO+7MlUE2lK1V5D9LijbvZeDgVGm2Wf9wOwJeWCNERK4uigiAUhrvITfocrrkIDZqvbNSnT20EYelM8RnJ0nVruxpnFapGXgXufJyELYMmobQS739Wg0f/f0OHQpEmzhJ+koC5/qMTJ11Y2ld2I3DKGEw/7wXCzxoA=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: pytest-dev/pytest-repeat
    python: 3.5
    condition: "$TOXENV = pytest30"
