language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
- nightly
env:
- TOXENV=pytest28
- TOXENV=pytest29
matrix:
  include:
  - python: 2.7
    env: TOXENV=flake8
  - python: 3.5
    env: TOXENV=flake8
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: davehunt
  password:
    secure: tsVlGuyYRBOTG8XA+RpQfW+6X4iN7pMwoCdlVKv/M3bi1eKvMSLk5ZB4M/mgrKm6UTeA5ataTlpgwDlaoVJnQd9olEubaHg6pP0ke8JPN4b465HnGMq9e083SZVdJ0BlbHWTiVWoh8v4w+5TiBpOsMJZhAsVF25tpb+TBuL/c4TFKsjD4iWoVvqQQO+p0yynan8KhqA/9N+N3tIDpG9Q6H3pazAbRmTgQU3+B8hV0U1x3go7ArDqhZ15++9vgifecp8PNxdqxIDTwZs/Ov9MK4kdej8SgP/uXQpQLMBoz4YwnxYE/7aAe9DEd+yIO62Lr8sp78nkI/PUbrm3DlZ+fcIcBi9/0Ezjolt7rQs8CViwwLBv2d736ICLMSKRAQ7n4835f9QEcsdAawV3rceyn/0ZwdknkIe8m8Dsz8RTesYH4QJIG5A+IOQ2949YY57euxO3ByIwscb6bvkAzcdkSABBKCEqA9UbqylNr86qoDBLaFQCQqUtW9Ew7yvnvoH8FkJJRcyFTXwFdUsn7pRBIL54Lt1npLqWjIPUqm1TBj8pp6kIDBLYRF9+H8McPjntPu2TsG0+yW08hcWtULf/0QelfM1RuwYwzhAaXiIZ8cTG6E8f0oocd2Dd2gjlxm32T172h/fjn4yyBCPcMdTAfA4J2DeOmHRqWb8wnid6Q50=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: pytest-dev/pytest-repeat
    python: 3.5
