language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3
env:
  - PYTEST=2.4.2
  - PYTEST=2.5.2
  - PYTEST=2.6.4
  - PYTEST=2.7.3
  - PYTEST=2.8.2
install:
  - pip install -q pytest==$PYTEST pytest-xdist
  - pip install -q -e .
script: py.test
